import { useState } from "react";
import Head from "next/head";
import Nav from "../components/Nav";
import axios from "axios";
import Uppy from "@uppy/core";
import { DashboardModal, useUppy } from "@uppy/react";
import UppyS3 from "@uppy/aws-s3";
import "@uppy/core/dist/style.css";
import "@uppy/dashboard/dist/style.css";
import { useSWRConfig } from "swr";
import S3List from "../components/S3List";

const queryKey = "uppy-signed-urls";

export default function Home() {
  const { mutate } = useSWRConfig();

  const [showUppyModal, setShowUppyModal] = useState(false);

  const uppy = useUppy(() =>
    new Uppy().use(UppyS3, {
      async getUploadParameters(file) {
        const response = await axios.post("/api/sign-url", {
          mimetype: file.type,
          folder: queryKey,
        });

        return {
          method: "PUT",
          url: response.data.url,
        };
      },
    })
  );

  uppy.on("complete", () => {
    setShowUppyModal(false);

    // Refetch
    mutate(queryKey);
  });

  return (
    <>
      <Head>
        <title>Uppy uploads</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4 flex flex-col items-center justify-center">
        <Nav />

        <DashboardModal
          open={showUppyModal}
          onRequestClose={() => setShowUppyModal(false)}
          uppy={uppy}
        />

        <div className="w-full max-w-screen-sm bg-slate-50 rounded p-4">
          <div className="flex flex-col justify-between gap-2">
            <h2 className="text-xl font-semibold">File uploader form</h2>
            <p className="mb-4">
              Using Uppy to upload directly to S3 with signed urls
            </p>
          </div>
          <hr />
          <button
            className="mt-4 px-2 py-1 bg-sky-500 hover:bg-sky-400 rounded text-white"
            onClick={() => setShowUppyModal(true)}
          >
            Open Uppy Uploader
          </button>
        </div>

        <S3List queryKey={queryKey} />
      </main>
    </>
  );
}
